model_names: ['logistic_regression', 'l1_logistic_regression','random_forest', 'xgboost', 'svm', 'spls_lda']
model_output_names: ['1_LR','2_L1_LR','3_RF','4_XGB','5_SVM','6_PLS_LDA']
feature_selection: [True, False, True, True, True, False]
base_data_folder: '../OUTPUT/UKB/ML/1_data/'
base_model_folder: '../OUTPUT/UKB/ML/2_models/'
base_plot_folder: '../OUTPUT/UKB/ML/3_summary_plots/'
features_to_bypass: '../DATA/UKB/ML/ML_quantitative_covariates.csv' #This refers to the quantitative features you should NOT pass to feature selection step
features_to_select: '../DATA/UKB/ML/ML_pp_names.csv' #This refers to the quantitative features you SHOULD pass to feature selection step

## For target variable = HCM_prevalent
# FOR DATA SPLITTING
# data_path: '../DATA/UKB/PROCESSED/2_5Y/ukb_ALLpanel_pp_hcm_covariates_bp_t2d_smoking_rcmmcov.tsv'
# folder_suffix: '1_hcm_cc_noprs/'

# FOR MODEL TRAINING
# target_variable: 'prevalent'

## For target variable = HCM incidence
# FOR DATA SPLITTING
data_path: '../DATA/UKB/PROCESSED/2_5Y/ukb_ALLpanel_pp_hcm_covariates_bp_t2d_smoking_rcmmcov_HCMdiagCox.tsv'
folder_suffix: '3_hcm_incident_noprs/'

# FOR MODEL TRAINING
target_variable: 'incident'
